#!/usr/bin/env bash
# fujinet_sync.sh -- refresh the vendored FujiNet Atari 7800 cartridge sources.
#
# Usage: ./fujinet_sync.sh [FUJINET_FIRMWARE] [FUJINET_CONFIG]
#   FUJINET_FIRMWARE  fujinet-firmware checkout with pico/atari-7800
#                     (default ~/Workspace/fujinet-firmware, branch add-atari7800)
#   FUJINET_CONFIG    fujinet-config checkout whose atari7800 CONFIG is baked
#                     into the firmware's fujiconfigrom.h (default ~/Workspace/fncfg-7800)
#
# The protocol (fujimail, fujibus), the mapper engine (a78map, a78map_db), the
# load sequence (fuji_load), the HSC's saves (hsc), the bus decode
# (a78_cart.h) and the baked CONFIG, loader and boot block are the cartridge
# firmware's own, copied verbatim plus the fujins.h include line. The device
# (fujinet.cpp/h), its link (fujilink.cpp/h) and the host interface
# (fujinet_host.h) are this fork's own and are never touched here. Run it,
# rebuild, commit.

set -euo pipefail
cd "$(dirname "$0")"

FW=${1:-$HOME/Workspace/fujinet-firmware}
CFG=${2:-$HOME/Workspace/fncfg-7800}
S="$FW/pico/atari-7800"
GEN="$S/build/gen"
[ -f "$GEN/fujiconfigrom.h" ] || GEN="$S/firmware/baked"

for f in fujimail fujibus a78map a78map_db fuji_load hsc; do
    cp "$S/firmware/src/$f.c" "$f.cpp"
done
for f in fujimail.h fujibus.h fuji_mailbox.h a78_cart.h a78map.h a78map_db.h fuji_load.h hsc.h; do
    cp "$S/firmware/include/$f" .
done
for f in fujiconfigrom.h a78loaderrom.h a78bootblk.h; do
    cp "$GEN/$f" .
done

# Give this port's copies of the shared protocol sources their own symbols,
# so they can never clash with the in-process FujiNet runtime or a sibling
# port in the same MAME tree.
{
    echo "/* GENERATED by fujinet_sync.sh -- do not edit. */"
    echo "#ifndef A78_FUJINS_H"
    echo "#define A78_FUJINS_H"
    for sym in fujimail_init fujimail_paint fujimail_read_hotspot fujimail_inbound \
               fujibus_build_request fujibus_parse_reply fujibus_selftest \
               fuji_load_init fuji_load_stage fuji_load_unstage \
               fuji_load_arm fuji_load_busy fuji_load_event fuji_load_ack \
               fuji_load_abort fuji_load_handover fuji_load_slices fuji_load_slice \
               hsc_init hsc_restore hsc_service hsc_save_chunk; do
        echo "#define $sym a78_$sym"
    done
    echo "#endif"
} > fujins.h

for f in fujimail.cpp fujimail.h fujibus.cpp fujibus.h fuji_load.cpp fuji_load.h hsc.cpp hsc.h; do
    if ! head -1 "$f" | grep -q fujins.h; then
        printf '#include "fujins.h"\n%s\n' "$(cat "$f")" > "$f.tmp"
        mv "$f.tmp" "$f"
    fi
done

{
    echo "# FujiNet Atari 7800 cartridge: where the vendored files in this directory came from."
    echo "# Regenerate with ./fujinet_sync.sh <fujinet-firmware checkout>."
    echo "firmware_url=https://github.com/FujiNetWIFI/fujinet-firmware"
    echo "firmware_branch=$(git -C "$FW" rev-parse --abbrev-ref HEAD)"
    echo "firmware_commit=$(git -C "$FW" rev-parse HEAD)"
    echo "firmware_dir=pico/atari-7800"
    echo "config_url=https://github.com/FujiNetWIFI/fujinet-config"
    echo "config_branch=$(git -C "$CFG" rev-parse --abbrev-ref HEAD)"
    echo "config_commit=$(git -C "$CFG" rev-parse HEAD)"
    echo "# sha256 of each vendored file as copied (before fork-owned edits):"
    for f in a78_cart.h a78bootblk.h a78loaderrom.h a78map.cpp a78map.h a78map_db.cpp a78map_db.h \
             fuji_load.cpp fuji_load.h fuji_mailbox.h fujibus.cpp fujibus.h fujiconfigrom.h \
             fujimail.cpp fujimail.h hsc.cpp hsc.h; do
        echo "sha256 $(sha256sum "$f" | cut -c1-64) $f"
    done
} > FUJINET_SOURCES
echo "fujinet_sync.sh: done"
