/* GENERATED by pico/atari-7800/emu/apply.sh -- do not edit. */
#ifndef A78_FUJINS_H
#define A78_FUJINS_H
#define fujimail_init a78_fujimail_init
#define fujimail_paint a78_fujimail_paint
#define fujimail_read_hotspot a78_fujimail_read_hotspot
#define fujimail_inbound a78_fujimail_inbound
#define fujibus_build_request a78_fujibus_build_request
#define fujibus_parse_reply a78_fujibus_parse_reply
#define fujibus_selftest a78_fujibus_selftest
#define fujitcp_init a78_fujitcp_init
#define fujitcp_active a78_fujitcp_active
#define fujitcp_close a78_fujitcp_close
#define fujitcp_transact a78_fujitcp_transact
#define fujitcp_send_bare a78_fujitcp_send_bare
#define fuji_load_init a78_fuji_load_init
#define fuji_load_stage a78_fuji_load_stage
#define fuji_load_unstage a78_fuji_load_unstage
#define fuji_load_arm a78_fuji_load_arm
#define fuji_load_busy a78_fuji_load_busy
#define fuji_load_event a78_fuji_load_event
#define fuji_load_ack a78_fuji_load_ack
#define fuji_load_abort a78_fuji_load_abort
#define fuji_load_handover a78_fuji_load_handover
#define fuji_load_slices a78_fuji_load_slices
#define fuji_load_slice a78_fuji_load_slice
#define hsc_init a78_hsc_init
#define hsc_restore a78_hsc_restore
#define hsc_service a78_hsc_service
#define hsc_save_chunk a78_hsc_save_chunk
#endif
